# Generated by Django 4.0.3 on 2022-03-20 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMbtiHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mbti', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mbti', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_mbti_type',
            },
        ),
    ]
